// change data columns

export const changeDataColumns = [
  {
    id: 1,
    columnNameKr: "현장",
    sequence: 1,
    pageType: 1,
    isActive: true,
    isMasterData: true,
    excelColumnName: "site",
    jsonKey: "site",
    isMandatory: true,
  },
  {
    id: 2,
    columnNameKr: "공정",
    sequence: 2,
    pageType: 1,
    isActive: true,
    isMasterData: true,
    excelColumnName: "process",
    jsonKey: "process",
    isMandatory: true,
  },
  {
    id: 3,
    columnNameKr: "유지보수 그룹",
    sequence: 3,
    pageType: 1,
    isActive: true,
    isMasterData: true,
    excelColumnName: "equipment",
    jsonKey: "maintGroup",
    isMandatory: true,
  },
  {
    id: 4,
    columnNameKr: "설비 코드",
    sequence: 4,
    pageType: 1,
    isActive: true,
    isMasterData: true,
    excelColumnName: "equipment_code",
    jsonKey: "equipmentCode",
    isMandatory: true,
  },
  {
    id: 5,
    columnNameKr: "설비 명",
    sequence: 5,
    pageType: 1,
    isActive: true,
    isMasterData: true,
    excelColumnName: "equipment_name",
    jsonKey: "equipmentName",
    isMandatory: true,
  },
  {
    id: 6,
    columnNameKr: "작업지시서 코드",
    sequence: 6,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "wo_code",
    jsonKey: "wOCode",
    isMandatory: false,
  },
  {
    id: 7,
    columnNameKr: "보고서",
    sequence: 7,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "report_content",
    jsonKey: "report",
    isMandatory: false,
  },
  {
    id: 8,
    columnNameKr: "BOM",
    sequence: 8,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "bom",
    jsonKey: "bom",
    isMandatory: false,
  },
  {
    id: 9,
    columnNameKr: "예비 부품",
    sequence: 9,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "spare part",
    jsonKey: "sparePart",
    isMandatory: false,
  },
  {
    id: 10,
    columnNameKr: "작업일자",
    sequence: 10,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "work_date",
    jsonKey: "workedOn",
    isMandatory: false,
  },
  {
    id: 11,
    columnNameKr: "작업",
    sequence: 11,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "work",
    jsonKey: "work",
    isMandatory: false,
  },
  {
    id: 12,
    columnNameKr: "작업 목적",
    sequence: 12,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "purpose",
    jsonKey: "purpose",
    isMandatory: false,
  },
  {
    id: 13,
    columnNameKr: "상황",
    sequence: 13,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "situation",
    jsonKey: "situation",
    isMandatory: false,
  },
  {
    id: 14,
    columnNameKr: "원인",
    sequence: 14,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "cause",
    jsonKey: "cause",
    isMandatory: false,
  },
  {
    id: 15,
    columnNameKr: "기존 하드웨어",
    sequence: 15,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "hw_was",
    jsonKey: "hwAsWas",
    isMandatory: false,
  },
  {
    id: 16,
    columnNameKr: "현 하드웨어",
    sequence: 16,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "hw_is",
    jsonKey: "hwAsIs",
    isMandatory: false,
  },
  {
    id: 17,
    columnNameKr: "기존 소프트웨어",
    sequence: 17,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "sw_was",
    jsonKey: "swAsWas",
    isMandatory: false,
  },
  {
    id: 18,
    columnNameKr: "현 소프트웨어",
    sequence: 18,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "sw_is",
    jsonKey: "swAsIs",
    isMandatory: false,
  },
  {
    id: 19,
    columnNameKr: "대표 작업",
    sequence: 19,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "rep_work",
    jsonKey: "representativeWork",
    isMandatory: true,
  },
  {
    id: 20,
    columnNameKr: "우선순위",
    sequence: 20,
    pageType: 1,
    isActive: true,
    isMasterData: true,
    excelColumnName: "priority",
    jsonKey: "priority",
    isMandatory: true,
  },
  {
    id: 21,
    columnNameKr: "구분",
    sequence: 21,
    pageType: 1,
    isActive: true,
    isMasterData: true,
    excelColumnName: "category",
    jsonKey: "category",
    isMandatory: true,
  },
];

export const changeFilterDataAndTableData = {
  process: [
    {
      id: 1,
      processName: "string",
      isChangedData: false,
      isSpecData: true,
    },
    {
      id: 2,
      processName: "03.성형",
      isChangedData: true,
      isSpecData: true,
    },
    {
      id: 3,
      processName: "08.소성",
      isChangedData: true,
      isSpecData: false,
    },
  ],
  site: [
    {
      id: 1,
      siteName: "string",
      processId: 1,
      isChangedData: false,
      isSpecData: true,
    },
    {
      id: 2,
      siteName: "A3.부산",
      processId: 2,
      isChangedData: true,
      isSpecData: true,
    },
    {
      id: 5,
      siteName: "A3.부산",
      processId: 3,
      isChangedData: true,
      isSpecData: false,
    },
    {
      id: 6,
      siteName: "A13.부산",
      processId: 3,
      isChangedData: true,
      isSpecData: false,
    },
  ],
  category: [
    {
      id: 1,
      categoryName: "보전성",
    },
    {
      id: 2,
      categoryName: "품질",
    },
  ],
  priority: [
    {
      id: 1,
      priorityName: "중요",
    },
    {
      id: 2,
      priorityName: "일반",
    },
  ],
  maintenance: [
    {
      id: 3,
      maintenanceGroupName: "string",
      processId: 1,
      isChangedData: false,
      isSpecData: true,
    },
    {
      id: 4,
      maintenanceGroupName: "0307. UT Coater",
      processId: 2,
      isChangedData: true,
      isSpecData: true,
    },
    {
      id: 7,
      maintenanceGroupName: "0806. RHK",
      processId: 3,
      isChangedData: true,
      isSpecData: false,
    },
    {
      id: 8,
      maintenanceGroupName: "0806. RHK1",
      processId: 3,
      isChangedData: true,
      isSpecData: false,
    },
  ],
  equipments: [
    {
      id: 1,
      equipmentName: "string",
      equipmentCode: "string",
      processId: 1,
      isChangedData: false,
      isSpecData: true,
    },
    {
      id: 3,
      equipmentName: "Coater(UT2)_IT___UT201",
      equipmentCode: "E2101703",
      processId: 2,
      isChangedData: true,
      isSpecData: false,
    },
    {
      id: 2,
      equipmentName: "Coater(UT)_전장___UT103",
      equipmentCode: "E1800379",
      processId: 2,
      isChangedData: true,
      isSpecData: true,
    },
    {
      id: 4,
      equipmentName: "열처리로(RHK)_17.5___HR55",
      equipmentCode: "E2500257",
      processId: 3,
      isChangedData: true,
      isSpecData: false,
    },
  ],
  representations: [
    {
      id: 5,
      representativeWorkName: "펌프 배선 플렉시블 관 적용",
      colorCode: "#0E7707",
      processId: 2,
      siteId: 2,
      maintenanceGroupId: 4,
    },
    {
      id: 6,
      representativeWorkName: "3기어 펌프 교체",
      colorCode: "#AD60B6",
      processId: 2,
      siteId: 2,
      maintenanceGroupId: 4,
    },
    {
      id: 7,
      representativeWorkName: "2차소성 타이머 유지시간 보정",
      colorCode: "#772022",
      processId: 3,
      siteId: 5,
      maintenanceGroupId: 7,
    },
    {
      id: 8,
      representativeWorkName: "2차소성 타이머 유지시간 보정",
      colorCode: "#3C9F6E",
      processId: 3,
      siteId: 6,
      maintenanceGroupId: 8,
    },
  ],
  changedDataJson: [
    {
      id: 1,
      content:
        '[{"id": 1, "bom": "abc", "site": "A3.부산", "work": "펌프 모터 배선 플렉시블관 적용", "cause": "배선이 방폭구역에서 노출돼 있었음", "hwAsIs": "배선에 플렉시블 관이 적용된 상태", "report": "1.목적: 25년 유기용제 취급공정 안전점검 계획에 모터 배선 노출 지적 발생 (방폭구역)\\n2.내용: 모터 배선 플렉시블 관 적용 \\n3.효과:\\n  3.1 개선전: 모터 배선 노출\\n  3.2 개선후: 모터 배선 플렉시블 관 적용\\n4.검증: 방폭사양 적", "swAsIs": "정보 없음", "wOCode": "W009114213", "hwAsWas": "배선이 노출된 상태", "process": "03.성형", "purpose": "25년 유기용제 취급공정 안전점검 계획에 따른 모터 배선 노출 지적 대응", "swAsWas": "정보 없음", "category": "보전성", "priority": "중요", "workedOn": "2024-07-29", "situation": "모터 배선이 노출된 상태", "sparePart": "abc", "maintGroup": "0307. UT Coater", "equipmentCode": "E2101703", "equipmentName": "Coater(UT2)_IT___UT201", "representativeWork": "펌프 배선 플렉시블 관 적용"}, {"id": 2, "bom": "bom", "site": "A3.부산", "work": "2Gear → 3Gear 펌프 교체", "cause": "노후된 2기어펌프가 공급 안정성을 저해함", "hwAsIs": "3기어 펌프", "report": "1.목적: 슬러리 공급 맥동을 최소화 하여 두께 산포 개선 \\n2.내용: 2기어펌프 → 3기어펌프 교체\\n * 3호기 간헐적 미노출 줄무늬 발생 시점에 교체함\\n3.효과:\\n  3.1 개선전: 2기어펌프 사용 (노후됨)\\n  3.2 개선후: 3기어 펌프 사용\\n4.검증: 줄무늬 및 두께측정데이터 양호", "swAsIs": "정보 없음", "wOCode": "W009114212", "hwAsWas": "2기어 펌프 (노후)", "process": "03.성형", "purpose": "슬러리 공급 맥동을 최소화 하여 두께 산포 개선", "swAsWas": "정보 없음", "category": "품질", "priority": "중요", "workedOn": "2024-07-30", "situation": "2기어펌프 사용(노후)으로 인한 슬러리 공급 맥동 및 간헐적 미노출 줄무늬 발생", "sparePart": "spare part", "maintGroup": "0307. UT Coater", "equipmentCode": "E1800379", "equipmentName": "Coater(UT)_전장___UT103", "representativeWork": "3기어 펌프 교체"}, {"id": 732, "bom": "abc", "site": "A3.부산", "work": "2차소성 급승온 종료 후 일반속도 원복 시점 타이머 정합성 보정", "cause": "업체의 임의변경으로 타이머 설정이 부적절하게 적용된 것", "hwAsIs": "2차소성 PEAK 부 롤러속도 300 → 15,000 → 2,000 → 300 가변 (2,000 → 300 변환 시 타이머 유지 11초)", "report": "□ 문제점 : 2차소성 PEAK 구간 냉각속도 > 승온속도 전환시점 불량으로 KEEP 유지시간 65초 > 80초, 15초 증가 (업체에서 임의변경)\\n□ 개선내용\\n   1) 변경 전 : 2차소성 PEAK부 롤러속도 300 > 15,000 > 2,000 > 300 가변 (2,000 > 300 가변시점은 타이머로 3.4초 유지)\\n   2) 변경 후 : 2차소성 PEAK부 롤러속도 300 > 15,000 > 2,000 > 300 가변 (2,000 > 300 가변시점은 타이머로 11초 유지)_잔여 롤러개수+부자재남은거리\\n   3) 기타(횡전개) : #55호기 단독\\n\\n※ 하기 기재 내용 추가 (안전/품질 필수 사항)\\n□ 최종점검자  \\n    - 설비 : 컴포넌트설비기술G 서영환, 이경상 프로 / 25년 11월 03일\\n    - 품질 : N/A\\n□ 점검 세부 내용\\n(점검결과 적합 : OK, 부적합 : NG, 해당없음 : N/A 기재)\\n1. 설비 안전장치 \\n   1) 인터락 도어 정상 작동 여부 (이상 동작 여부 점검)\\n      ① 설비 가동시 도어잠금 장치 설비는 도어 Open이 안되는지? OK\\n      ② 도어 Open시 설비가 Stop을 하는지? OK\\n      ③ (Robot) 설치 장비는  Door 개방 후 수동 조작시 동작하는지? OK\\n   2) Area Sensor 및 비상정지 S/W 동작\\n      ① 안전센서 정상 작동 여부 OK\\n      ② 센서 감지시 설비가 Stop이 정상적으로 작동 하는지? OK\\n      ③ 비상정지 S/W 작동시 알람이 뜨고 설비가 Stop 하는지? N/A (고온설비 평가불가)\\n2. 품질 결과\\n  - 해당공정 MPQA 측정 Data 1 - 글로벌기술G 검토중", "swAsIs": "정보 없음", "wOCode": "W009114214", "hwAsWas": "2차소성 PEAK 부 롤러속도 300 → 15,000 → 2,000 → 300 가변 (2,000 → 300 변환 시 타이머 유지 3.4초)", "process": "08.소성", "purpose": "급승온 종료 후 일반속도로 복귀 시점의 타이머 정합성을 맞춰 KEEP 유지시간을 정상화하기 위함", "swAsWas": "정보 없음", "category": "품질", "priority": "일반", "workedOn": "2024-08-30", "situation": "2차소성 PEAK 구간에서 냉각속도가 승온속도 전환시점에 불량을 일으켜 KEEP 유지시간이 65초에서 80초로 15초 증가함", "sparePart": "abc", "maintGroup": "0806. RHK", "equipmentCode": "E2500257", "equipmentName": "열처리로(RHK)_17.5___HR55", "representativeWork": "2차소성 타이머 유지시간 보정"}, {"id": 735, "bom": "agbc", "site": "A13.부산", "work": "2차소성 급승온 종료 후 일반속도 원복 시점 타이머 정합성 보정", "cause": "업체의 임의변경으로 타이머 설정이 부적절하게 적용된 것", "hwAsIs": "2차소성 PEAK 부 롤러속도 300 → 15,000 → 2,000 → 300 가변 (2,000 → 300 변환 시 타이머 유지 11초)", "report": "□ 문제점 : 2차소성 PEAK 구간 냉각속도 > 승온속도 전환시점 불량으로 KEEP 유지시간 65초 > 80초, 15초 증가 (업체에서 임의변경)\\n□ 개선내용\\n   1) 변경 전 : 2차소성 PEAK부 롤러속도 300 > 15,000 > 2,000 > 300 가변 (2,000 > 300 가변시점은 타이머로 3.4초 유지)\\n   2) 변경 후 : 2차소성 PEAK부 롤러속도 300 > 15,000 > 2,000 > 300 가변 (2,000 > 300 가변시점은 타이머로 11초 유지)_잔여 롤러개수+부자재남은거리\\n   3) 기타(횡전개) : #55호기 단독\\n\\n※ 하기 기재 내용 추가 (안전/품질 필수 사항)\\n□ 최종점검자  \\n    - 설비 : 컴포넌트설비기술G 서영환, 이경상 프로 / 25년 11월 03일\\n    - 품질 : N/A\\n□ 점검 세부 내용\\n(점검결과 적합 : OK, 부적합 : NG, 해당없음 : N/A 기재)\\n1. 설비 안전장치 \\n   1) 인터락 도어 정상 작동 여부 (이상 동작 여부 점검)\\n      ① 설비 가동시 도어잠금 장치 설비는 도어 Open이 안되는지? OK\\n      ② 도어 Open시 설비가 Stop을 하는지? OK\\n      ③ (Robot) 설치 장비는  Door 개방 후 수동 조작시 동작하는지? OK\\n   2) Area Sensor 및 비상정지 S/W 동작\\n      ① 안전센서 정상 작동 여부 OK\\n      ② 센서 감지시 설비가 Stop이 정상적으로 작동 하는지? OK\\n      ③ 비상정지 S/W 작동시 알람이 뜨고 설비가 Stop 하는지? N/A (고온설비 평가불가)\\n2. 품질 결과\\n  - 해당공정 MPQA 측정 Data 1 - 글로벌기술G 검토중", "swAsIs": "정보 없음", "wOCode": "W009114215", "hwAsWas": "2차소성 PEAK 부 롤러속도 300 → 15,000 → 2,000 → 300 가변 (2,000 → 300 변환 시 타이머 유지 3.4초)", "process": "08.소성", "purpose": "급승온 종료 후 일반속도로 복귀 시점의 타이머 정합성을 맞춰 KEEP 유지시간을 정상화하기 위함", "swAsWas": "정보 없음", "category": "품질", "priority": "일반", "workedOn": "2024-10-30", "situation": "2차소성 PEAK 구간에서 냉각속도가 승온속도 전환시점에 불량을 일으켜 KEEP 유지시간이 65초에서 80초로 15초 증가함", "sparePart": "abc", "maintGroup": "0806. RHK1", "equipmentCode": "E2500257", "equipmentName": "열처리로(RHK)_17.5___HR55", "representativeWork": "2차소성 타이머 유지시간 보정"}]',
    },
  ],
};

export default {
  changeDataColumns,
  changeFilterDataAndTableData,
};
