// change data columns

export const changeDataColumns = [
  {
    id: 1,
    columnNameKr: "현장",
    sequence: 1,
    pageType: 1,
    isActive: true,
    isMasterData: true,
    excelColumnName: "site",
    jsonKey: "site",
    isMandatory: true,
  },
  {
    id: 2,
    columnNameKr: "공정",
    sequence: 2,
    pageType: 1,
    isActive: true,
    isMasterData: true,
    excelColumnName: "process",
    jsonKey: "process",
    isMandatory: true,
  },
  {
    id: 3,
    columnNameKr: "유지보수 그룹",
    sequence: 3,
    pageType: 1,
    isActive: true,
    isMasterData: true,
    excelColumnName: "equipment",
    jsonKey: "maintGroup",
    isMandatory: true,
  },
  {
    id: 4,
    columnNameKr: "설비 코드",
    sequence: 4,
    pageType: 1,
    isActive: true,
    isMasterData: true,
    excelColumnName: "equipment_code",
    jsonKey: "equipmentCode",
    isMandatory: true,
  },
  {
    id: 5,
    columnNameKr: "설비 명",
    sequence: 5,
    pageType: 1,
    isActive: true,
    isMasterData: true,
    excelColumnName: "equipment_name",
    jsonKey: "equipmentName",
    isMandatory: true,
  },
  {
    id: 6,
    columnNameKr: "작업지시서 코드",
    sequence: 6,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "wo_code",
    jsonKey: "wOCode",
    isMandatory: false,
  },
  {
    id: 7,
    columnNameKr: "보고서",
    sequence: 7,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "report_content",
    jsonKey: "report",
    isMandatory: false,
  },
  {
    id: 8,
    columnNameKr: "BOM",
    sequence: 8,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "bom",
    jsonKey: "bom",
    isMandatory: false,
  },
  {
    id: 9,
    columnNameKr: "예비 부품",
    sequence: 9,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "spare part",
    jsonKey: "sparePart",
    isMandatory: false,
  },
  {
    id: 10,
    columnNameKr: "작업일자",
    sequence: 10,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "work_date",
    jsonKey: "workedOn",
    isMandatory: false,
  },
  {
    id: 11,
    columnNameKr: "작업",
    sequence: 11,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "work",
    jsonKey: "work",
    isMandatory: false,
  },
  {
    id: 12,
    columnNameKr: "작업 목적",
    sequence: 12,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "purpose",
    jsonKey: "purpose",
    isMandatory: false,
  },
  {
    id: 13,
    columnNameKr: "상황",
    sequence: 13,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "situation",
    jsonKey: "situation",
    isMandatory: false,
  },
  {
    id: 14,
    columnNameKr: "원인",
    sequence: 14,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "cause",
    jsonKey: "cause",
    isMandatory: false,
  },
  {
    id: 15,
    columnNameKr: "기존 하드웨어",
    sequence: 15,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "hw_was",
    jsonKey: "hwAsWas",
    isMandatory: false,
  },
  {
    id: 16,
    columnNameKr: "현 하드웨어",
    sequence: 16,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "hw_is",
    jsonKey: "hwAsIs",
    isMandatory: false,
  },
  {
    id: 17,
    columnNameKr: "기존 소프트웨어",
    sequence: 17,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "sw_was",
    jsonKey: "swAsWas",
    isMandatory: false,
  },
  {
    id: 18,
    columnNameKr: "현 소프트웨어",
    sequence: 18,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "sw_is",
    jsonKey: "swAsIs",
    isMandatory: false,
  },
  {
    id: 19,
    columnNameKr: "대표 작업",
    sequence: 19,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "rep_work",
    jsonKey: "representativeWork",
    isMandatory: true,
  },
  {
    id: 20,
    columnNameKr: "우선순위",
    sequence: 20,
    pageType: 1,
    isActive: true,
    isMasterData: true,
    excelColumnName: "priority",
    jsonKey: "priority",
    isMandatory: true,
  },
  {
    id: 21,
    columnNameKr: "구분",
    sequence: 21,
    pageType: 1,
    isActive: true,
    isMasterData: true,
    excelColumnName: "category",
    jsonKey: "category",
    isMandatory: true,
  },
];

export const changeFilterDataAndTableData = {
  process: [
    {
      id: 1,
      processName: "string",
      isChangedData: false,
      isSpecData: true,
    },
    {
      id: 2,
      processName: "03.성형",
      isChangedData: true,
      isSpecData: true,
    },
    {
      id: 3,
      processName: "08.소성",
      isChangedData: true,
      isSpecData: false,
    },
  ],
  site: [
    {
      id: 1,
      siteName: "string",
      processId: 1,
      isChangedData: false,
      isSpecData: true,
    },
    {
      id: 2,
      siteName: "A3.부산",
      processId: 2,
      isChangedData: true,
      isSpecData: true,
    },
    {
      id: 5,
      siteName: "A3.부산",
      processId: 3,
      isChangedData: true,
      isSpecData: false,
    },
    {
      id: 6,
      siteName: "A13.부산",
      processId: 3,
      isChangedData: true,
      isSpecData: false,
    },
  ],
  category: [
    {
      id: 1,
      categoryName: "보전성",
    },
    {
      id: 2,
      categoryName: "품질",
    },
  ],
  priority: [
    {
      id: 1,
      priorityName: "필수",
    },
    {
      id: 2,
      priorityName: "중요",
    },
    {
      id: 3,
      priorityName: "일반",
    },
    {
      id: 4,
      priorityName: "제외",
    },
  ],
  maintenance: [
    {
      id: 3,
      maintenanceGroupName: "string",
      processId: 1,
      isChangedData: false,
      isSpecData: true,
    },
    {
      id: 4,
      maintenanceGroupName: "0307. UT Coater",
      processId: 2,
      isChangedData: true,
      isSpecData: true,
    },
    {
      id: 7,
      maintenanceGroupName: "0806. RHK",
      processId: 3,
      isChangedData: true,
      isSpecData: false,
    },
    {
      id: 8,
      maintenanceGroupName: "0806. RHK1",
      processId: 3,
      isChangedData: true,
      isSpecData: false,
    },
  ],
  equipments: [
    {
      id: 1,
      equipmentName: "string",
      equipmentCode: "string",
      processId: 1,
      isChangedData: false,
      isSpecData: true,
    },
    {
      id: 3,
      equipmentName: "Coater(UT2)_IT___UT201",
      equipmentCode: "E2101703",
      processId: 2,
      isChangedData: true,
      isSpecData: false,
    },
    {
      id: 2,
      equipmentName: "Coater(UT)_전장___UT103",
      equipmentCode: "E1800379",
      processId: 2,
      isChangedData: true,
      isSpecData: true,
    },
    {
      id: 4,
      equipmentName: "열처리로(RHK)_17.5___HR55",
      equipmentCode: "E2500257",
      processId: 3,
      isChangedData: true,
      isSpecData: false,
    },
  ],
  representations: [
    {
      id: 5,
      representativeWorkName: "펌프 배선 플렉시블 관 적용",
      processId: 2,
      siteId: 2,
      maintenanceGroupId: 4,
    },
    {
      id: 6,
      representativeWorkName: "3기어 펌프 교체",
      processId: 2,
      siteId: 2,
      maintenanceGroupId: 4,
    },
    {
      id: 7,
      representativeWorkName: "2차소성 타이머 유지시간 보정",
      processId: 3,
      siteId: 5,
      maintenanceGroupId: 7,
    },
    {
      id: 8,
      representativeWorkName: "2차소성 타이머 유지시간 보정",
      processId: 3,
      siteId: 6,
      maintenanceGroupId: 8,
    },
  ],
  changedDataJson: [
    {
      id: 1,
      content:
        '[{"id": 1, "bom": "abc", "site": "A3.부산", "work": "펌프 모터 배선 플렉시블관 적용", "cause": "배선이 방폭구역에서 노출돼 있었음", "hwAsIs": "배선에 플렉시블 관이 적용된 상태", "report": "1.목적: 안전점검 지적 대응", "swAsIs": "정보 없음", "wOCode": "W009114213", "woType": "BM", "hwAsWas": "배선이 노출된 상태", "process": "03.성형", "purpose": "안전점검 대응", "swAsWas": "정보 없음", "category": "보전성", "priority": "중요", "workedOn": "2026-08-07", "situation": "모터 배선이 노출된 상태", "sparePart": "abc", "maintGroup": "0307. UT Coater", "equipmentCode": "E2101703", "equipmentName": "Coater(UT2)_IT___UT201", "representativeWork": "펌프 배선 플렉시블 관 적용"}, {"id": 101, "bom": "abc", "site": "A3.부산", "work": "펌프 모터 점검", "cause": "정기 점검", "hwAsIs": "정상", "report": "정기점검 완료", "swAsIs": "정보 없음", "wOCode": "W009114220", "woType": "CM", "hwAsWas": "정상", "process": "03.성형", "purpose": "정기 점검", "swAsWas": "정보 없음", "category": "보전성", "priority": "일반", "workedOn": "2026-05-01", "situation": "정기점검 대상", "sparePart": "abc", "maintGroup": "0307. UT Coater", "equipmentCode": "E2101703", "equipmentName": "Coater(UT2)_IT___UT201", "representativeWork": "펌프 배선 플렉시블 관 적용"}, {"id": 102, "bom": "abc", "site": "A3.부산", "work": "펌프 모터 배선 보강", "cause": "노후화 마모", "hwAsIs": "보강 완료", "report": "배선 보강 완료", "swAsIs": "정보 없음", "wOCode": "W009114221", "woType": "CM", "hwAsWas": "마모", "process": "03.성형", "purpose": "배선 보강", "swAsWas": "정보 없음", "category": "보전성", "priority": "일반", "workedOn": "2026-04-23", "situation": "배선 마모", "sparePart": "abc", "maintGroup": "0307. UT Coater", "equipmentCode": "E2101703", "equipmentName": "Coater(UT2)_IT___UT201", "representativeWork": "펌프 배선 플렉시블 관 적용"}, {"id": 103, "bom": "abc", "site": "A3.부산", "work": "펌프 모터 교체", "cause": "소음 발생", "hwAsIs": "신규 모터", "report": "모터 교체", "swAsIs": "정보 없음", "wOCode": "W009114222", "woType": "BM", "hwAsWas": "구형 모터", "process": "03.성형", "purpose": "모터 교체", "swAsWas": "정보 없음", "category": "보전성", "priority": "일반", "workedOn": "2026-01-05", "situation": "소음 심함", "sparePart": "abc", "maintGroup": "0307. UT Coater", "equipmentCode": "E2101703", "equipmentName": "Coater(UT2)_IT___UT201", "representativeWork": "펌프 배선 플렉시블 관 적용"}, {"id": 104, "bom": "abc", "site": "A3.부산", "work": "초기 점검", "cause": "설치 초기", "hwAsIs": "정상", "report": "초기 점검", "swAsIs": "정보 없음", "wOCode": "W009114223", "woType": "CM", "hwAsWas": "정상", "process": "03.성형", "purpose": "초기 점검", "swAsWas": "정보 없음", "category": "보전성", "priority": "일반", "workedOn": "2024-01-01", "situation": "초기 가동", "sparePart": "abc", "maintGroup": "0307. UT Coater", "equipmentCode": "E2101703", "equipmentName": "Coater(UT2)_IT___UT201", "representativeWork": "펌프 배선 플렉시블 관 적용"}, {"id": 2, "bom": "bom", "site": "A3.부산", "work": "2Gear → 3Gear 펌프 교체", "cause": "노후 2기어펌프", "hwAsIs": "3기어 펌프", "report": "펌프 교체 완료", "swAsIs": "정보 없음", "wOCode": "W009114212", "woType": "BM", "hwAsWas": "2기어 펌프", "process": "03.성형", "purpose": "두께 산포 개선", "swAsWas": "정보 없음", "category": "품질", "priority": "일반", "workedOn": "2026-07-15", "situation": "줄무늬 발생", "sparePart": "spare part", "maintGroup": "0307. UT Coater", "equipmentCode": "E1800379", "equipmentName": "Coater(UT)_전장___UT103", "representativeWork": "3기어 펌프 교체"}, {"id": 201, "bom": "bom", "site": "A3.부산", "work": "3기어 펌프 유압 조정", "cause": "유압 편차", "hwAsIs": "유압 정상화", "report": "유압 조정 완료", "swAsIs": "정보 없음", "wOCode": "W009114224", "woType": "CM", "hwAsWas": "유압 저하", "process": "03.성형", "purpose": "유압 안정화", "swAsWas": "정보 없음", "category": "품질", "priority": "일반", "workedOn": "2026-03-10", "situation": "유압 불안정", "sparePart": "spare part", "maintGroup": "0307. UT Coater", "equipmentCode": "E1800379", "equipmentName": "Coater(UT)_전장___UT103", "representativeWork": "3기어 펌프 교체"}]',
    },
  ],
};

export default {
  changeDataColumns,
  changeFilterDataAndTableData,
};
