// change data columns

export const changeDataColumns = [
  {
    id: 1,
    columnNameKr: "현장",
    sequence: 1,
    pageType: 1,
    isActive: true,
    isMasterData: true,
    excelColumnName: "site",
    jsonKey: "site",
  },
  {
    id: 2,
    columnNameKr: "공정",
    sequence: 2,
    pageType: 1,
    isActive: true,
    isMasterData: true,
    excelColumnName: "process",
    jsonKey: "process",
  },
  {
    id: 3,
    columnNameKr: "유지보수 그룹",
    sequence: 3,
    pageType: 1,
    isActive: true,
    isMasterData: true,
    excelColumnName: "equipment",
    jsonKey: "maintGroup",
  },
  {
    id: 4,
    columnNameKr: "설비 코드",
    sequence: 4,
    pageType: 1,
    isActive: true,
    isMasterData: true,
    excelColumnName: "equipment_code",
    jsonKey: "equipmentCode",
  },
  {
    id: 5,
    columnNameKr: "설비 명",
    sequence: 5,
    pageType: 1,
    isActive: true,
    isMasterData: true,
    excelColumnName: "equipment_name",
    jsonKey: "equipmentName",
  },
  {
    id: 6,
    columnNameKr: "작업지시서 코드",
    sequence: 6,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "wo_code",
    jsonKey: "wOCode",
  },
  {
    id: 7,
    columnNameKr: "보고서",
    sequence: 7,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "report_content",
    jsonKey: "report",
  },
  {
    id: 8,
    columnNameKr: "BOM",
    sequence: 8,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "bom",
    jsonKey: "bom",
  },
  {
    id: 9,
    columnNameKr: "예비 부품",
    sequence: 9,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "spare part",
    jsonKey: "sparePart",
  },
  {
    id: 10,
    columnNameKr: "작업일자",
    sequence: 10,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "work_date",
    jsonKey: "workedOn",
  },
  {
    id: 11,
    columnNameKr: "작업",
    sequence: 11,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "work",
    jsonKey: "work",
  },
  {
    id: 12,
    columnNameKr: "작업 목적",
    sequence: 12,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "purpose",
    jsonKey: "purpose",
  },
  {
    id: 13,
    columnNameKr: "상황",
    sequence: 13,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "situation",
    jsonKey: "situation",
  },
  {
    id: 14,
    columnNameKr: "원인",
    sequence: 14,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "cause",
    jsonKey: "cause",
  },
  {
    id: 15,
    columnNameKr: "기존 하드웨어",
    sequence: 15,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "hw_was",
    jsonKey: "hwAsWas",
  },
  {
    id: 16,
    columnNameKr: "현 하드웨어",
    sequence: 16,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "hw_is",
    jsonKey: "hwAsIs",
  },
  {
    id: 17,
    columnNameKr: "기존 소프트웨어",
    sequence: 17,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "sw_was",
    jsonKey: "swAsWas",
  },
  {
    id: 18,
    columnNameKr: "현 소프트웨어",
    sequence: 18,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "sw_is",
    jsonKey: "swAsIs",
  },
  {
    id: 19,
    columnNameKr: "대표 작업",
    sequence: 19,
    pageType: 1,
    isActive: true,
    isMasterData: false,
    excelColumnName: "rep_work",
    jsonKey: "representativeWork",
  },
  {
    id: 20,
    columnNameKr: "우선순위",
    sequence: 20,
    pageType: 1,
    isActive: true,
    isMasterData: true,
    excelColumnName: "priority",
    jsonKey: "priority",
  },
  {
    id: 21,
    columnNameKr: "구분",
    sequence: 21,
    pageType: 1,
    isActive: true,
    isMasterData: true,
    excelColumnName: "category",
    jsonKey: "category",
  },
];

export const changeFilterDataAndTableData = {
  process: [
    {
      id: 7,
      processName: "04.성형",
    },
    {
      id: 8,
      processName: "03.성형",
    },
  ],
  site: [
    {
      id: 18,
      siteName: "d3.부산",
      processId: 7,
    },
    {
      id: 19,
      siteName: "a3.부산",
      processId: 8,
    },
  ],
  category: [
    {
      id: 5,
      categoryName: "보전성",
    },
    {
      id: 6,
      categoryName: "품질",
    },
  ],
  priority: [
    {
      id: 1,
      priorityName: "중요",
    },
  ],
  maintenance: [
    {
      id: 20,
      maintenanceGroupName: "1307. ut coater",
      processId: 7,
    },
    {
      id: 21,
      maintenanceGroupName: "0307. ut coater",
      processId: 8,
    },
  ],
  equipments: [
    {
      id: 78,
      equipmentName: "coater(ut2)_it___ut20k",
      equipmentCode: "e2101741",
      processId: 7,
    },
    {
      id: 79,
      equipmentName: "coater(ut)_전장___ut103",
      equipmentCode: "e1800379",
      processId: 8,
    },
  ],
  representations: [
    {
      id: 80,
      representativeWorkName: "펌프 배선 플렉시블 관 적용",
      processId: 7,
      siteId: 18,
      maintenanceGroupId: 20,
    },
    {
      id: 81,
      representativeWorkName: "3기어 펌프 교체",
      processId: 8,
      siteId: 19,
      maintenanceGroupId: 21,
    },
  ],
  changedDataJson: [
    {
      id: 6,
      content:
        '[{"id": 1, "bom": "", "site": "d3.부산", "work": "펌프 모터 배선 플렉시블관 적용", "cause": "배선이 방폭구역에서 노출돼 있었음", "hwAsIs": "배선에 플렉시블 관이 적용된 상태", "report": "1.목적: 25년 유기용제 취급공정 안전점검 계획에 모터 배선 노출 지적 발생 (방폭구역)\\n2.내용: 모터 배선 플렉시블 관 적용 \\n3.효과:\\n  3.1 개선전: 모터 배선 노출\\n  3.2 개선후: 모터 배선 플렉시블 관 적용\\n4.검증: 방폭사양 적", "swAsIs": "정보 없음", "wOCode": "W009114213", "hwAsWas": "배선이 노출된 상태", "process": "04.성형", "purpose": "25년 유기용제 취급공정 안전점검 계획에 따른 모터 배선 노출 지적 대응", "swAsWas": "정보 없음", "category": "보전성", "priority": "중요", "workedOn": "2026-01-28", "situation": "모터 배선이 노출된 상태", "sparePart": "", "maintGroup": "1307. ut coater", "equipmentCode": "e2101741", "equipmentName": "coater(ut2)_it___ut20k", "representativeWork": "펌프 배선 플렉시블 관 적용"}, {"id": 2, "bom": "", "site": "a3.부산", "work": "2Gear → 3Gear 펌프 교체", "cause": "노후된 2기어펌프가 공급 안정성을 저해함", "hwAsIs": "3기어 펌프", "report": "1.목적: 슬러리 공급 맥동을 최소화 하여 두께 산포 개선 \\n2.내용: 2기어펌프 → 3기어펌프 교체\\n * 3호기 간헐적 미노출 줄무늬 발생 시점에 교체함\\n3.효과:\\n  3.1 개선전: 2기어펌프 사용 (노후됨)\\n  3.2 개선후: 3기어 펌프 사용\\n4.검증: 줄무늬 및 두께측정데이터 양호", "swAsIs": "정보 없음", "wOCode": "W009114212", "hwAsWas": "2기어 펌프 (노후)", "process": "03.성형", "purpose": "슬러리 공급 맥동을 최소화 하여 두께 산포 개선", "swAsWas": "정보 없음", "category": "품질", "priority": "중요", "workedOn": "2026-01-28", "situation": "2기어펌프 사용(노후)으로 인한 슬러리 공급 맥동 및 간헐적 미노출 줄무늬 발생", "sparePart": "", "maintGroup": "0307. ut coater", "equipmentCode": "e1800379", "equipmentName": "coater(ut)_전장___ut103", "representativeWork": "3기어 펌프 교체"}]',
    },
  ],
};

export default {
  changeDataColumns,
  changeFilterDataAndTableData,
};
