export const sampleApiPayloadData = [
  {
    versionId: 44,
    version: "v44",
    from: "0001-01-01T00:00:00",
    to: "0001-01-01T00:00:00",
    period: "2026-01-01 ~ 2026-12-31",
    equipmentCount: 2,
    appliedCount: 4,
    notAppliedCount: 3,
    excludedCount: 3,
    createdBy: 0,
    createdOn: "2026-08-01T10:00:00",
    registeredBy: "admin",
    registeredAt: "2026-08-01 10:00:00",
    modifiedBy: 0,
    modifiedOn: "2026-08-01T10:00:00",
    editedBy: "admin",
    editedAt: "2026-08-01 10:00:00",
    changedDataJson: [
      {
        id: 1223,
        site: null,
        process: "05. Laminator",
        maintGroup: "0503. RP (440)_2ROLL",
        equipmentCode: "3R2053",
        equipmentName: "Coater(3R2)_450___3R2053",
        report: "设备改善：3R2-53 课题号：CX-26-1-06，本社推进项目，横展开使用备件适配器,备件出库安装",
        bom: "",
        sparePart: "",
        work: "수평 전개를 위한 부품 어댑터 사용 및 설치",
        purpose: "정보 없음",
        situation: "정보 없음",
        cause: "정보 없음",
        hwAsWas: "정보 없음",
        hwAsIs: "부품 어댑터 적용",
        swAsWas: "정보 없음",
        swAsIs: "정보 없음",
        representativeWork: "부품 어댑터 사용 및 설치",
        priority: "General",
        category: "Others",
        isApplicable: true,
      },
      {
        id: 1224,
        site: null,
        process: "05. Laminator",
        maintGroup: "0503. RP (440)_2ROLL",
        equipmentCode: "3R2055",
        equipmentName: "Coater(3R2)_450___3R2055",
        report: "1.目的:设备改善：课题号：CX-26-1-06，本社推进项目，横展开备件真空发生器数量缺少3R2-55出库1EA使用\n2.内容:设备改善：课题号：CX-26-1-06，本社推进项目，横展开备件真空发生器数量缺少3R2-55出库1EA使用\n3.效果:\n  3.1 As-was:\n  3.2 To-Be:更换后点检Ok\n4.验证:更换后点检Ok",
        bom: "",
        sparePart: "",
        work: "진공 발생기 3R2-55 1EA 교체",
        purpose: "설비 개선 및 부족한 3R2-55 진공 발생기 부품 확보",
        situation: "3R2-55 진공 발생기 부품 1EA 부족으로 인한 설비 가동 불가 가능성",
        cause: "재고 부족으로 해당 부품이 출고되지 않음",
        hwAsWas: "3R2-55 진공 발생기 부품 미설치(부재)",
        hwAsIs: "3R2-55 진공 발생기 1EA 설치 및 교체 완료",
        swAsWas: "정보 없음",
        swAsIs: "정보 없음",
        representativeWork: "진공 발생기 3R2-55 1EA 교체",
        priority: "Important",
        category: "Productivity",
        isApplicable: true,
      },
      {
        id: 1225,
        site: null,
        process: "05. Laminator",
        maintGroup: "0503. RP (440)_2ROLL",
        equipmentCode: "3R2053",
        equipmentName: "Coater(3R2)_450___3R2053",
        report: "1.目的:设备改善：课题号：CX-26-1-06，本社推进项目，横展开备件真空发生器数量缺少3R2-53出库1EA使用\n2.内容:CX-26-1-06，本社推进项目，横展开备件真空发生器数量缺少3R2-53出库1EA使用\n3.效果:\n  3.1 As-was:\n  3.2 To-Be:\n4.验证:更换后点检OK",
        bom: "",
        sparePart: "",
        work: "CX-26-1-06 장비 개선(진공 발생기 3R2-53 교체)",
        purpose: "진공 발생기 3R2-53 부품 부족 해소 및 설비 가동 확보",
        situation: "진공 발생기 3R2-53 부품이 1EA 부족하여 교체 불가 상태",
        cause: "재고에서 해당 부품이 부족함",
        hwAsWas: "3R2-53 진공 발생기 부품이 없거나 미설치 상태",
        hwAsIs: "3R2-53 진공 발생기 1EA를 설치하여 정상 가동",
        swAsWas: "정보 없음",
        swAsIs: "정보 없음",
        representativeWork: "진공 발생기 3R2-53 교체",
        priority: "Important",
        category: "Productivity",
        isApplicable: true,
      },
      {
        id: 1226,
        site: null,
        process: "05. Laminator",
        maintGroup: "0503. RP (440)_2ROLL",
        equipmentCode: "3R2055",
        equipmentName: "Coater(3R2)_450___3R2055",
        report: "设备改善：课题号：CX-26-1-06，本社推进项目，横展开备件粒子计数器3R2-55安装使用",
        bom: "",
        sparePart: "",
        work: "3R2-55 粒子计数器(横展开备件) 설치 및 사용",
        purpose: "粒子计数을 통한 품질 모니터링 및 관리",
        situation: "정보 없음",
        cause: "정보 없음",
        hwAsWas: "정보 없음",
        hwAsIs: "3R2-55 粒子计数器 설치",
        swAsWas: "정보 없음",
        swAsIs: "정보 없음",
        representativeWork: "3R2-55 粒子计数器 설치 및 사용",
        priority: "General",
        category: "Quality",
        isApplicable: true,
      },
      {
        id: 1227,
        site: null,
        process: "05. Laminator",
        maintGroup: "0503. RP (440)_2ROLL",
        equipmentCode: "3R2053",
        equipmentName: "Coater(3R2)_450___3R2053",
        report: "设备改善：课题号：CX-26-1-06，本社推进项目，横展开备件粒子计数器3R2-53安装使用",
        bom: "",
        sparePart: "",
        work: "3R2‑53 입자계수기(예비 부품)의 가로 확장 설치 및 사용",
        purpose: "입자계수기 설치를 통해 공정 품질 관리 및 오염 모니터링 강화",
        situation: "정보 없음",
        cause: "정보 없음",
        hwAsWas: "정보 없음",
        hwAsIs: "3R2‑53 입자계수기 설치 (가로 확장된 위치에 배치)",
        swAsWas: "정보 없음",
        swAsIs: "정보 없음",
        representativeWork: "3R2‑53 입자계수기 가로 확장 설치",
        priority: "General",
        category: "Quality",
        isApplicable: false,
        reasoning: "Importance Average",
      },
      {
        id: 1228,
        site: null,
        process: "05. Laminator",
        maintGroup: "0503. RP (440)_2ROLL",
        equipmentCode: "3R2055",
        equipmentName: "Coater(3R2)_450___3R2055",
        report: "设备改善：课题号：CX-26-1-06，本社推进项目，横展开备件调压阀，3R2-55出库1EA出库安装",
        bom: "",
        sparePart: "",
        work: "横展开备件调压阀 설치",
        purpose: "설비 압력 조절 기능 확보 및 안정화",
        situation: "정보 없음",
        cause: "정보 없음",
        hwAsWas: "정보 없음",
        hwAsIs: "3R2-55 型 압력 조정 밸브 1EA 설치",
        swAsWas: "정보 없음",
        swAsIs: "정보 없음",
        representativeWork: "横展开备件调压阀 설치",
        priority: "General",
        category: "Others",
        isApplicable: false,
        reasoning: "Importance Average",
      },
      {
        id: 1229,
        site: null,
        process: "05. Laminator",
        maintGroup: "0503. RP (440)_2ROLL",
        equipmentCode: "3R2053",
        equipmentName: "Coater(3R2)_450___3R2053",
        report: "设备改善：课题号：CX-26-1-06，本社推进项目，横展开备件调压阀，3R2-53出库1EA出库安装",
        bom: "",
        sparePart: "",
        work: "가로 전개용 예비 부품 압력 조절 밸브 설치",
        purpose: "설비의 압력 제어를 통해 운영 안정성 및 공정 품질 확보",
        situation: "정보 없음",
        cause: "정보 없음",
        hwAsWas: "정보 없음",
        hwAsIs: "압력 조절 밸브가 설치된 상태",
        swAsWas: "정보 없음",
        swAsIs: "정보 없음",
        representativeWork: "압력 조절 밸브 설치",
        priority: "General",
        category: "Others",
        isApplicable: false,
        reasoning: "Importance Average",
      },
    ],
  },
  {
    versionId: 45,
    version: "v45",
    from: "0001-01-01T00:00:00",
    to: "0001-01-01T00:00:00",
    period: "2026-02-01 ~ 2026-12-31",
    equipmentCount: 0,
    appliedCount: 0,
    notAppliedCount: 0,
    excludedCount: 0,
    createdBy: 0,
    createdOn: "2026-08-02T10:00:00",
    registeredBy: "admin",
    registeredAt: "2026-08-02 10:00:00",
    modifiedBy: 0,
    modifiedOn: "2026-08-02T10:00:00",
    editedBy: "admin",
    editedAt: "2026-08-02 10:00:00",
    changedDataJson: [],
  },
  {
    versionId: 46,
    version: "v46",
    from: "0001-01-01T00:00:00",
    to: "0001-01-01T00:00:00",
    period: "2026-03-01 ~ 2026-12-31",
    equipmentCount: 0,
    appliedCount: 0,
    notAppliedCount: 0,
    excludedCount: 0,
    createdBy: 0,
    createdOn: "2026-08-03T10:00:00",
    registeredBy: "admin",
    registeredAt: "2026-08-03 10:00:00",
    modifiedBy: 0,
    modifiedOn: "2026-08-03T10:00:00",
    editedBy: "admin",
    editedAt: "2026-08-03 10:00:00",
    changedDataJson: [],
  },
  {
    versionId: 47,
    version: "v47",
    from: "0001-01-01T00:00:00",
    to: "0001-01-01T00:00:00",
    period: "2026-04-01 ~ 2026-12-31",
    equipmentCount: 2,
    appliedCount: 7,
    notAppliedCount: 0,
    excludedCount: 0,
    createdBy: 0,
    createdOn: "2026-08-04T10:00:00",
    registeredBy: "admin",
    registeredAt: "2026-08-04 10:00:00",
    modifiedBy: 0,
    modifiedOn: "2026-08-04T10:00:00",
    editedBy: "admin",
    editedAt: "2026-08-04 10:00:00",
    changedDataJson: [
      {
        id: 1223,
        site: null,
        process: "05. Laminator",
        maintGroup: "0503. RP (440)_2ROLL",
        equipmentCode: "3R2053",
        equipmentName: "Coater(3R2)_450___3R2053",
        report: "设备改善：3R2-53 课题号：CX-26-1-06，本社推进项目，横展开使用备件适配器,备件出库安装",
        bom: "",
        sparePart: "",
        work: "수평 전개를 위한 부품 어댑터 사용 및 설치",
        purpose: "정보 없음",
        situation: "정보 없음",
        cause: "정보 없음",
        hwAsWas: "정보 없음",
        hwAsIs: "부품 어댑터 적용",
        swAsWas: "정보 없음",
        swAsIs: "정보 없음",
        representativeWork: "부품 어댑터 사용 및 설치",
        priority: "General",
        category: "Others",
        isApplicable: true,
      },
      {
        id: 1224,
        site: null,
        process: "05. Laminator",
        maintGroup: "0503. RP (440)_2ROLL",
        equipmentCode: "3R2055",
        equipmentName: "Coater(3R2)_450___3R2055",
        report: "1.目的:设备改善：课题号：CX-26-1-06，本社推进项目，横展开备件真空发生器数量缺少3R2-55出库1EA使用\n2.内容:设备改善：课题号：CX-26-1-06，本社推进项目，横展开备件真空发生器数量缺少3R2-55出库1EA使用\n3.效果:\n  3.1 As-was:\n  3.2 To-Be:更换后点检Ok\n4.验证:更换后点检Ok",
        bom: "",
        sparePart: "",
        work: "진공 발생기 3R2-55 1EA 교체",
        purpose: "설비 개선 및 부족한 3R2-55 진공 발생기 부품 확보",
        situation: "3R2-55 진공 발생기 부품 1EA 부족으로 인한 설비 가동 불가 가능성",
        cause: "재고 부족으로 해당 부품이 출고되지 않음",
        hwAsWas: "3R2-55 진공 발생기 부품 미설치(부재)",
        hwAsIs: "3R2-55 진공 발생기 1EA 설치 및 교체 완료",
        swAsWas: "정보 없음",
        swAsIs: "정보 없음",
        representativeWork: "진공 발생기 3R2-55 1EA 교체",
        priority: "Important",
        category: "Productivity",
        isApplicable: true,
      },
      {
        id: 1225,
        site: null,
        process: "05. Laminator",
        maintGroup: "0503. RP (440)_2ROLL",
        equipmentCode: "3R2053",
        equipmentName: "Coater(3R2)_450___3R2053",
        report: "1.目的:设备改善：课题号：CX-26-1-06，本社推进项目，横展开备件真空发生器数量缺少3R2-53出库1EA使用\n2.内容:CX-26-1-06，本社推进项目，横展开备件真空发生器数量缺少3R2-53出库1EA使用\n3.效果:\n  3.1 As-was:\n  3.2 To-Be:\n4.验证:更换后点检OK",
        bom: "",
        sparePart: "",
        work: "CX-26-1-06 장비 개선(진공 발생기 3R2-53 교체)",
        purpose: "진공 발생기 3R2-53 부품 부족 해소 및 설비 가동 확보",
        situation: "진공 발생기 3R2-53 부품이 1EA 부족하여 교체 불가 상태",
        cause: "재고에서 해당 부품이 부족함",
        hwAsWas: "3R2-53 진공 발생기 부품이 없거나 미설치 상태",
        hwAsIs: "3R2-53 진공 발생기 1EA를 설치하여 정상 가동",
        swAsWas: "정보 없음",
        swAsIs: "정보 없음",
        representativeWork: "진공 발생기 3R2-53 교체",
        priority: "Important",
        category: "Productivity",
        isApplicable: true,
      },
      {
        id: 1226,
        site: null,
        process: "05. Laminator",
        maintGroup: "0503. RP (440)_2ROLL",
        equipmentCode: "3R2055",
        equipmentName: "Coater(3R2)_450___3R2055",
        report: "设备改善：课题号：CX-26-1-06，本社推进项目，横展开备件粒子计数器3R2-55安装使用",
        bom: "",
        sparePart: "",
        work: "3R2-55 粒子计数器(横展开备件) 설치 및 사용",
        purpose: "粒子计数을 통한 품질 모니터링 및 관리",
        situation: "정보 없음",
        cause: "정보 없음",
        hwAsWas: "정보 없음",
        hwAsIs: "3R2-55 粒子计数器 설치",
        swAsWas: "정보 없음",
        swAsIs: "정보 없음",
        representativeWork: "3R2-55 粒子计数器 설치 및 사용",
        priority: "General",
        category: "Quality",
        isApplicable: true,
      },
      {
        id: 1227,
        site: null,
        process: "05. Laminator",
        maintGroup: "0503. RP (440)_2ROLL",
        equipmentCode: "3R2053",
        equipmentName: "Coater(3R2)_450___3R2053",
        report: "设备改善：课题号：CX-26-1-06，本社推进项目，横展开备件粒子计数器3R2-53安装使用",
        bom: "",
        sparePart: "",
        work: "3R2‑53 입자계수기(예비 부품)의 가로 확장 설치 및 사용",
        purpose: "입자계수기 설치를 통해 공정 품질 관리 및 오염 모니터링 강화",
        situation: "정보 없음",
        cause: "정보 없음",
        hwAsWas: "정보 없음",
        hwAsIs: "3R2‑53 입자계수기 설치 (가로 확장된 위치에 배치)",
        swAsWas: "정보 없음",
        swAsIs: "정보 없음",
        representativeWork: "3R2‑53 입자계수기 가로 확장 설치",
        priority: "General",
        category: "Quality",
        isApplicable: true,
      },
      {
        id: 1228,
        site: null,
        process: "05. Laminator",
        maintGroup: "0503. RP (440)_2ROLL",
        equipmentCode: "3R2055",
        equipmentName: "Coater(3R2)_450___3R2055",
        report: "设备改善：课题号：CX-26-1-06，本社推进项目，横展开备件调压阀，3R2-55出库1EA出库安装",
        bom: "",
        sparePart: "",
        work: "横展开备件调压阀 설치",
        purpose: "설비 압력 조절 기능 확보 및 안정화",
        situation: "정보 없음",
        cause: "정보 없음",
        hwAsWas: "정보 없음",
        hwAsIs: "3R2-55 型 압력 조정 밸브 1EA 설치",
        swAsWas: "정보 없음",
        swAsIs: "정보 없음",
        representativeWork: "横展开备件调压阀 설치",
        priority: "General",
        category: "Others",
        isApplicable: true,
      },
      {
        id: 1229,
        site: null,
        process: "05. Laminator",
        maintGroup: "0503. RP (440)_2ROLL",
        equipmentCode: "3R2053",
        equipmentName: "Coater(3R2)_450___3R2053",
        report: "设备改善：课题号：CX-26-1-06，本社推进项目，横展开备件调压阀，3R2-53出库1EA出库安装",
        bom: "",
        sparePart: "",
        work: "가로 전개용 예비 부품 압력 조절 밸브 설치",
        purpose: "설비의 압력 제어를 통해 운영 안정성 및 공정 품질 확보",
        situation: "정보 없음",
        cause: "정보 없음",
        hwAsWas: "정보 없음",
        hwAsIs: "압력 조절 밸브가 설치된 상태",
        swAsWas: "정보 없음",
        swAsIs: "정보 없음",
        representativeWork: "압력 조절 밸브 설치",
        priority: "General",
        category: "Others",
        isApplicable: true,
      },
    ],
  },
];

export const mpManagementStaticData = sampleApiPayloadData.map((v) => ({
  id: v.versionId,
  versionId: v.versionId,
  version: v.version,
  period: v.period,
  appliedCount: v.appliedCount,
  excludedCount: v.excludedCount,
  notAppliedCount: v.notAppliedCount,
  facilityId: v.equipmentCount || 2,
  consultation: "—",
  registeredBy: v.registeredBy,
  registeredAt: v.registeredAt,
  editedBy: v.editedBy,
  editedAt: v.editedAt,
  changedDataJson: v.changedDataJson,
  changeDataList: v.changedDataJson,
  rows: v.changedDataJson,
}));

export const sampleChangeMatrixEquipmentData = [
  {
    change_history_id: 1515,
    site_id: 1,
    site_name: "A1.수원",
    equipment_code: "H0303001",
    equipment_name: "Coater(3R2)_450___C1HH-R2-01",
    equipment_id: 1,
    representative_work_name: "형광등 LED 교체",
    status: "w/o applied",
    category_id: 1652,
    category_name: "보전성",
    priority_id: 1652,
    priority_name: "일반",
    work_date: "2019-04-24T00:00:00",
    rep_work_id: 1652,
    version_id: 2,
  },
  {
    change_history_id: 1516,
    site_id: 2,
    site_name: "A3.부산",
    equipment_code: "H0306001",
    equipment_name: "R203-R2 Coater-4세대",
    equipment_id: 2,
    representative_work_name: "성형기 가스 검출기 검교정",
    status: "w/o applied",
    category_id: 1653,
    category_name: "품질",
    priority_id: 1653,
    priority_name: "일반",
    work_date: "2020-06-03T00:00:00",
    rep_work_id: 1653,
    version_id: 2,
  },
  {
    change_history_id: 1517,
    site_id: 1,
    site_name: "A1.수원",
    equipment_code: "3R2053",
    equipment_name: "Coater(3R2)_450___3R2053",
    equipment_id: 3,
    representative_work_name: "부품 어댑터 사용 및 설치",
    status: "w/o applied",
    category_id: 1652,
    category_name: "보전성",
    priority_id: 1652,
    priority_name: "일반",
    work_date: "2026-08-01T00:00:00",
    rep_work_id: 1652,
    version_id: 0,
  },
  {
    change_history_id: 1518,
    site_id: 2,
    site_name: "A3.부산",
    equipment_code: "3R2055",
    equipment_name: "Coater(3R2)_450___3R2055",
    equipment_id: 4,
    representative_work_name: "진공 발생기 3R2-55 1EA 교체",
    status: "w/o applied",
    category_id: 1653,
    category_name: "품질",
    priority_id: 1653,
    priority_name: "일반",
    work_date: "2026-08-02T00:00:00",
    rep_work_id: 1653,
    version_id: 0,
  },
  {
    change_history_id: 1519,
    site_id: 3,
    site_name: "A2.울산",
    equipment_code: "E2101703",
    equipment_name: "Coater(UT2)_IT___UT201",
    equipment_id: 5,
    representative_work_name: "펌프 배선 플렉시블 관 적용",
    status: "w/o applied",
    category_id: 1652,
    category_name: "보전성",
    priority_id: 1652,
    priority_name: "중요",
    work_date: "2026-08-07T00:00:00",
    rep_work_id: 1652,
    version_id: 0,
  },
  {
    change_history_id: 1520,
    site_id: 3,
    site_name: "A2.울산",
    equipment_code: "E1800379",
    equipment_name: "Coater(UT)_전장___UT103",
    equipment_id: 6,
    representative_work_name: "3기어 펌프 교체",
    status: "w/o applied",
    category_id: 1653,
    category_name: "품질",
    priority_id: 1653,
    priority_name: "일반",
    work_date: "2026-07-15T00:00:00",
    rep_work_id: 1653,
    version_id: 0,
  },
];

export const sampleCompareRows = [
  {
    repWork: "수평 전개를 위한 부품 어댑터 사용 및 설치",
    purpose: "정보 없음",
    problem: "정보 없음",
    cause: "정보 없음",
    bom: "—",
    materialName: "Coater(3R2)_450___3R2053",
    hwBefore: "정보 없음",
    importance: "General",
    effect: "Others",
    v1Status: "Applied",
    v2Status: "Applied",
  },
  {
    repWork: "진공 발생기 3R2-55 1EA 교체",
    purpose: "설비 개선 및 부족한 3R2-55 진공 발생기 부품 확보",
    problem: "3R2-55 진공 발생기 부품 1EA 부족으로 인한 설비 가동 불가 가능성",
    cause: "재고 부족으로 해당 부품이 출고되지 않음",
    bom: "—",
    materialName: "Coater(3R2)_450___3R2055",
    hwBefore: "3R2-55 진공 발생기 부품 미설치(부재)",
    importance: "Important",
    effect: "Productivity",
    v1Status: "Applied",
    v2Status: "Applied",
  },
  {
    repWork: "CX-26-1-06 장비 개선(진공 발생기 3R2-53 교체)",
    purpose: "진공 발생기 3R2-53 부품 부족 해소 및 설비 가동 확보",
    problem: "진공 발생기 3R2-53 부품이 1EA 부족하여 교체 불가 상태",
    cause: "재고에서 해당 부품이 부족함",
    bom: "—",
    materialName: "Coater(3R2)_450___3R2053",
    hwBefore: "3R2-53 진공 발생기 부품이 없거나 미설치 상태",
    importance: "Important",
    effect: "Productivity",
    v1Status: "Applied",
    v2Status: "Applied",
  },
  {
    repWork: "3R2-55 粒子计数器(横展开备件) 설치 및 사용",
    purpose: "粒子计数을 통한 품질 모니터링 및 관리",
    problem: "정보 없음",
    cause: "정보 없음",
    bom: "—",
    materialName: "Coater(3R2)_450___3R2055",
    hwBefore: "정보 없음",
    importance: "General",
    effect: "Quality",
    v1Status: "Applied",
    v2Status: "Applied",
  },
  {
    repWork: "3R2‑53 입자계수기(예비 부품)의 가로 확장 설치 및 사용",
    purpose: "입자계수기 설치를 통해 공정 품질 관리 및 오염 모니터링 강화",
    problem: "정보 없음",
    cause: "정보 없음",
    bom: "—",
    materialName: "Coater(3R2)_450___3R2053",
    hwBefore: "정보 없음",
    importance: "General",
    effect: "Quality",
    v1Status: "Not applied",
    v2Status: "Applied",
  },
];

