// change data columns

export const specDataColumns = [
  {
    id: 24,
    columnNameKr: "공정",
    sequence: 1,
    pageType: 2,
    isActive: true,
    isMasterData: true,
    excelColumnName: "공정",
    jsonKey: "process",
    isMandatory: true,
  },
  {
    id: 28,
    columnNameKr: "현장",
    sequence: 2,
    pageType: 2,
    isActive: true,
    isMasterData: true,
    excelColumnName: "site",
    jsonKey: "site",
    isMandatory: true,
  },
  {
    id: 25,
    columnNameKr: "보전타입",
    sequence: 3,
    pageType: 2,
    isActive: true,
    isMasterData: true,
    excelColumnName: "보전타입",
    jsonKey: "maintGroup",
    isMandatory: true,
  },
  {
    id: 29,
    columnNameKr: "설비코드",
    sequence: 4,
    pageType: 2,
    isActive: true,
    isMasterData: true,
    excelColumnName: "설비코드",
    jsonKey: "equipmentCode",
    isMandatory: true,
  },
  {
    id: 30,
    columnNameKr: "설비명",
    sequence: 5,
    pageType: 2,
    isActive: true,
    isMasterData: true,
    excelColumnName: "설비명",
    jsonKey: "equipmentName",
    isMandatory: true,
  },
  {
    id: 26,
    columnNameKr: "버전",
    sequence: 6,
    pageType: 2,
    isActive: true,
    isMasterData: false,
    excelColumnName: "버전",
    jsonKey: "version",
    isMandatory: true,
  },
  {
    id: 31,
    columnNameKr: "검수 항목(단위)",
    sequence: 7,
    pageType: 2,
    isActive: true,
    isMasterData: false,
    excelColumnName: "검수 항목(단위) ",
    jsonKey: "specName",
    isMandatory: true,
  },
  {
    id: 32,
    columnNameKr: "Spec.",
    sequence: 8,
    pageType: 2,
    isActive: true,
    isMasterData: false,
    excelColumnName: "Spec.",
    jsonKey: "specValue",
    isMandatory: true,
  },
];
export const specFilterDataAndTableData = {
  process: [
    {
      id: 1,
      processName: "string",
      isChangedData: false,
      isSpecData: true,
    },
    {
      id: 2,
      processName: "03.성형",
      isChangedData: true,
      isSpecData: true,
    },
    {
      id: 3,
      processName: "08.소성",
      isChangedData: true,
      isSpecData: false,
    },
  ],
  site: [
    {
      id: 1,
      siteName: "string",
      processId: 1,
      isChangedData: false,
      isSpecData: true,
    },
    {
      id: 2,
      siteName: "A3.부산",
      processId: 2,
      isChangedData: true,
      isSpecData: true,
    },
    {
      id: 5,
      siteName: "A3.부산",
      processId: 3,
      isChangedData: true,
      isSpecData: false,
    },
    {
      id: 6,
      siteName: "A13.부산",
      processId: 3,
      isChangedData: true,
      isSpecData: false,
    },
  ],
  category: [
    {
      id: 1,
      categoryName: "보전성",
    },
    {
      id: 2,
      categoryName: "품질",
    },
  ],
  priority: [
    {
      id: 1,
      priorityName: "중요",
    },
    {
      id: 2,
      priorityName: "일반",
    },
  ],
  maintenance: [
    {
      id: 3,
      maintenanceGroupName: "string",
      processId: 1,
      isChangedData: false,
      isSpecData: true,
    },
    {
      id: 4,
      maintenanceGroupName: "0307. UT Coater",
      processId: 2,
      isChangedData: true,
      isSpecData: true,
    },
    {
      id: 7,
      maintenanceGroupName: "0806. RHK",
      processId: 3,
      isChangedData: true,
      isSpecData: false,
    },
    {
      id: 8,
      maintenanceGroupName: "0806. RHK1",
      processId: 3,
      isChangedData: true,
      isSpecData: false,
    },
  ],
  equipments: [
    {
      id: 1,
      equipmentName: "string",
      equipmentCode: "string",
      processId: 1,
      isChangedData: false,
      isSpecData: true,
    },
    {
      id: 3,
      equipmentName: "Coater(UT2)_IT___UT201",
      equipmentCode: "E2101703",
      processId: 2,
      isChangedData: true,
      isSpecData: false,
    },
    {
      id: 2,
      equipmentName: "Coater(UT)_전장___UT103",
      equipmentCode: "E1800379",
      processId: 2,
      isChangedData: true,
      isSpecData: true,
    },
    {
      id: 4,
      equipmentName: "열처리로(RHK)_17.5___HR55",
      equipmentCode: "E2500257",
      processId: 3,
      isChangedData: true,
      isSpecData: false,
    },
  ],
  representations: [
    {
      id: 5,
      representativeWorkName: "펌프 배선 플렉시블 관 적용",
      colorCode: "#0E7707",
      processId: 2,
      siteId: 2,
      maintenanceGroupId: 4,
    },
    {
      id: 6,
      representativeWorkName: "3기어 펌프 교체",
      colorCode: "#AD60B6",
      processId: 2,
      siteId: 2,
      maintenanceGroupId: 4,
    },
    {
      id: 7,
      representativeWorkName: "2차소성 타이머 유지시간 보정",
      colorCode: "#772022",
      processId: 3,
      siteId: 5,
      maintenanceGroupId: 7,
    },
    {
      id: 8,
      representativeWorkName: "2차소성 타이머 유지시간 보정",
      colorCode: "#3C9F6E",
      processId: 3,
      siteId: 6,
      maintenanceGroupId: 8,
    },
  ],
  specDataJson: [
    {
      id: 1,
      content:
        '[{"id": 1, "site": "string", "process": "string", "version": "string", "specName": "string", "specValue": "string", "maintGroup": "string", "equipmentCode": "string", "equipmentName": "string"}, {"id": 2, "site": "A3.부산", "process": "03.성형", "version": "string", "specName": "string", "specValue": "string", "maintGroup": "0307. UT Coater", "equipmentCode": "E1800379", "equipmentName": "Coater(UT)_전장___UT103"}]',
    },
  ],
};

export default {
  specDataColumns,
  specFilterDataAndTableData,
};
